version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    assignees:
      - sato-toma
    labels:
      - "dependabot"
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    open-pull-requests-limit: 20
    labels:
      - "dependabot"
    assignees:
      - sato-toma